script: "bundle exec rake db:drop db:create db:migrate test"
rvm:
  - 1.8.7
  - 1.9.2
  - jruby
  - ree
notifications:
  recipients:
    - enrique@cloverinteractive.com
    - alejandro@cloverinteractive.com

