require 'spec_helper'

describe Page do
  let( :page ) { create :page }

  describe "name" do
    it "must be present" do
      page.name = nil
      page.should be_invalid
    end

    it "must be unique" do
      new_page = build :page, name: page.name
      new_page.should be_invalid
    end
  end

  describe "slug" do
    it "must be autogenerated" do
      page.save!
      page.slug.should be_present
    end
  end

  it "should belong to one section" do
    page = build :page, name: 'test_name', content: 'Test content', section: nil
    page.should be_invalid
  end

  it "should accept keywords" do
    page.keyword_list = 'this, are, some, keywords'
    page.should be_valid
  end
end
