require 'spec_helper'

describe Page do
  before :each do
    @page = Factory.create :page
  end

  describe "name" do
    it "must be present" do
      @page.name = nil
      @page.should be_invalid
    end

    it "must be unique" do
      page = Factory.build :page
      page.should be_invalid
    end
  end

  describe "url_name" do
    it "must be autogenerated" do
      @page.url_name.should be_present
    end
  end

  it "should belong to one section" do
    page =  Page.new :name => 'test_name', :content => 'Test content'
    page.should be_invalid

    @page.section.should be_present
  end

  it "should accept keywords" do
    @page.keyword_list = 'this, are, some, keywords'
    @page.should be_valid
    @page.save.should == true
  end
end
